# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-30 21:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NovoAluno',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('sobrenome', models.CharField(max_length=100, verbose_name='Sobrenome')),
                ('sexo', models.CharField(max_length=100, verbose_name='Sexo')),
                ('email', models.EmailField(max_length=100, verbose_name='E-mail')),
                ('telefone', models.IntegerField(verbose_name='Telefone')),
                ('endereco', models.CharField(max_length=100, verbose_name='Endereço')),
                ('cep', models.IntegerField(verbose_name='CEP')),
                ('cidade', models.CharField(max_length=100, verbose_name='Cidade')),
                ('estado', models.CharField(max_length=100, verbose_name='Estado')),
                ('curso', models.CharField(max_length=100, verbose_name='Curso')),
            ],
        ),
    ]
